apiVersion: batch/v1
kind: Job
metadata:
  name: stan-test
  namespace: ucsd-haosulab
spec:
  ttlSecondsAfterFinished: 86400 # Wait one day to delete completed jobs
  template:
    metadata:
      labels:
        nautilus.io/rl: "true"
    spec:
      containers:
        - name: gpu-container
          image: mutongzhou/ms2-rk
          # imagePullPolicy: Always
          command:
            - bash
            - -c
            - |
              pip uninstall mani_skill2
              rm -rf ~/ManiSkill2
              wandb login 4e2cc88659e965fd46f8cea8dc1c94c875f99e8c
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              source ~/.zshrc
              git clone https://github.com/tongzhoumu/ManiSkill2.git
              git clone https://github.com/stasio6/roboml.git
              cd
              cd ManiSkill2
              git pull
              cd 
              cd stasio6
              git pull
              PYTHONPATH=~/ManiSkill2:$PYTHONPATH {command}
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "1"
              memory: "1Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            # - name: cephfs-slow
            #   mountPath: /cephfs_slow
            - name: cephfs-fast
              mountPath: /cephfs_fast
      volumes:
        - name: dshm # shared memory, required for the multi-worker dataloader
          emptyDir:
            medium: Memory
        # - name: cephfs-slow
        #   persistentVolumeClaim:
        #     claimName: tmu-slow-vol
        - name: cephfs-fast
          persistentVolumeClaim:
            claimName: tmu-fast-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nautilus.io/group
                    operator: In
                    values:
                      - haosu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-2080-Ti
              # - matchExpressions:
              #     - key: nvidia.com/gpu.product
              #       operator: In
              #       values:
              #         - NVIDIA-A10
              #         - NVIDIA-GeForce-RTX-3090
              #         # - NVIDIA-RTX-A6000
              #         # - NVIDIA-A100-SXM4-80GB
  backoffLimit: 1 # The number of attempts to restart after crash